version: '3.1'

services:
  # api:
  #   image: steezclick/node-web-app
  #   depends_on:
  #     - mongo
  #   environment:
  #     PORT: 8080
  #     MONGO_URI:

  mongo:
    image: mongo:4.2.3-bionic
    restart: always
    ports:
      - 27017:27017
