version: '3.1'

services:
  api:
    image: steezclick/node-web-app:2.0
    depends_on:
      - mongo
    environment:
      PORT: 8080
      MONGO_URI: mongodb://localhost/test

  mongo:
    image: mongo:4.2.3-bionic
    restart: always
    ports:
      - 27017:27017
