version: '3.8'

services:
  api:
    build:
      context: .
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongo/test

  mongo:
    image: mongo:4.2.3-bionic
    restart: always
